# Generated by Django 3.2.3 on 2021-05-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('caller_id', models.CharField(default='', max_length=100)),
                ('helper_id', models.CharField(default='', max_length=100)),
                ('src_address', models.CharField(default='', max_length=100)),
                ('dest_address', models.CharField(default='', max_length=100)),
                ('coin_cost', models.IntegerField(default=0)),
                ('descrption', models.CharField(default='', max_length=1000)),
                ('secret_info', models.CharField(default='', max_length=1000)),
                ('order_status', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('star_level', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=1000)),
                ('credit', models.IntegerField(default=100)),
                ('coin_num', models.IntegerField(default=20)),
                ('gender', models.CharField(default='', max_length=100)),
                ('call_order_list', models.CharField(default='', max_length=1000)),
                ('take_order_list', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
