# Generated by Django 3.2.3 on 2021-05-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkusender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='descrption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='caller_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='helper_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
