# Generated by Django 3.2.3 on 2021-05-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkusender', '0002_auto_20210528_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
