# Generated by Django 3.2.3 on 2021-05-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkusender', '0003_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_wait',
            fields=[
                ('order_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('order_id_int', models.IntegerField(default=0)),
            ],
        ),
    ]
