# Generated by Django 3.2.3 on 2021-05-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkusender', '0004_order_wait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
