# Generated by Django 3.2.3 on 2021-05-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkusender', '0005_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='history_order_list',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
