# Generated by Django 3.2.3 on 2021-05-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkusender', '0006_user_history_order_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global',
            name='value',
        ),
    ]
