# Generated by Django 3.2.3 on 2021-05-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkusender', '0007_remove_global_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_wait',
            name='order_id_int',
        ),
    ]
