# Generated by Django 3.2.3 on 2021-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkusender', '0008_remove_order_wait_order_id_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='vale',
            field=models.IntegerField(default=0),
        ),
    ]
