# Generated by Django 3.2.3 on 2021-05-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkusender', '0009_global_vale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global',
            old_name='vale',
            new_name='value',
        ),
    ]
