# Generated by Django 3.2.3 on 2021-06-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkusender', '0010_rename_vale_global_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(default=0),
        ),
    ]
